#!/usr/bin/python
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Feature Not Implemented</title>")
print("<style>")
print("body { font-family: Arial, sans-serif; }")
print("h1 { color: red; }")
print("p { font-size: 18px; }")
print("</style>")
print("</head>")
print("<body>")
print("<h1>Feature Not Implemented</h1>")
print("<p>This feature has not been implemented yet, please check back later.</p>")
print("</body>")
print("</html>")
